services:
  de_postgres:
    image: postgres:13
    container_name: de_postgres
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - pg_network
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
     external: true
     name: pg_data

networks:
  pg_network:
    external: true
    name: airflow_default