services:
  postgres:
    image: postgres:13
    container_name: de_postgres
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - pg_network
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

volumes:
  pg_data:
     external: true
     name: pg_data

networks:
  pg_network: